export const courses = [
  {
    id: "ai-basics",
    title: "AI Basics Training Course",
    trainer: "Trainer A",
    category: "AI",
    description:
      "Build a practical foundation in AI concepts, prompting and responsible use.",
    price: 80,
    rating: 4.0,
    purchased: false,
    learningStatus: "Unwatched",
    format: "Self-paced",
    deliveryModes: ["cloud"],
    delivery: "Hosted on CoLearnX",
    tags: ["beginner", "responsible AI"],
    prerequisites: "No prior AI experience required",
    capacity: null,
    enrolled: 0,
    structure: "Single course",
    duration: 45,
    watched: 0,
    downloaded: false,
    modules: [
      "AI foundations and terminology",
      "Prompt practice",
      "Responsible AI checklist",
    ],
  },
  {
    id: "web-design",
    title: "Web Design Bootcamp",
    trainer: "Trainer B",
    category: "Design",
    description:
      "A guided course covering layout, typography, responsive design and critique.",
    price: 120,
    rating: 4.7,
    purchased: true,
    learningStatus: "Watching",
    format: "Self-paced",
    deliveryModes: ["cloud"],
    delivery: "Hosted on CoLearnX",
    purchasedAt: "2026-08-28T12:00:00+08:00",
    tags: ["responsive design", "portfolio"],
    prerequisites: "Basic familiarity with web pages",
    capacity: null,
    enrolled: 24,
    structure: "4-module series",
    duration: 180,
    watched: 45,
    downloaded: false,
    modules: [
      "Layout foundations",
      "Typography and colour",
      "Responsive design",
      "Portfolio critique",
    ],
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity Intro",
    trainer: "Trainer C",
    category: "Security",
    description:
      "A live introduction to everyday cyber risks and practical defensive habits.",
    price: 100,
    rating: 4.9,
    purchased: true,
    learningStatus: "Unwatched",
    format: "External LIVE",
    deliveryModes: ["live"],
    delivery: "Zoom",
    tags: ["security", "beginner"],
    prerequisites: "No prerequisites",
    capacity: 40,
    enrolled: 32,
    structure: "Single session",
    duration: 60,
    watched: 0,
    downloaded: false,
    startsAt: "2026-09-08T20:00:00+08:00",
    replay: false,
    modules: ["Live cybersecurity essentials"],
  },
  {
    id: "javascript-starter",
    title: "JavaScript Starter",
    trainer: "Trainer D",
    category: "Code",
    description:
      "Learn JavaScript fundamentals through four short live workshops.",
    price: 70,
    rating: 4.1,
    purchased: true,
    learningStatus: "Unwatched",
    format: "External LIVE",
    deliveryModes: ["live", "record"],
    delivery: "Microsoft Teams",
    tags: ["JavaScript", "workshop"],
    prerequisites: "A modern browser and basic HTML knowledge",
    capacity: 30,
    enrolled: 27,
    structure: "4-session series",
    duration: 120,
    watched: 0,
    downloaded: false,
    startsAt: "2026-09-16T09:00:00+08:00",
    replay: true,
    modules: [
      "Variables and data types",
      "Functions",
      "Arrays and objects",
      "Browser project",
    ],
  },
];

export const publishedItems = [
  {
    id: "PUB-COURSE-WEB",
    kind: "course",
    ownerRole: "Trainer",
    marketplaceId: "web-design",
    title: "Web Design Bootcamp",
    category: "Design",
    format: "Self-paced",
    price: 120,
    description:
      "A guided course covering layout, typography, responsive design and critique.",
    modules: [
      "Layout foundations",
      "Typography and colour",
      "Responsive design",
      "Portfolio critique",
    ],
    status: "Published",
    visibility: "Public marketplace",
    updatedAt: "18 Aug 2026",
  },
  {
    id: "PUB-COURSE-AI",
    kind: "course",
    ownerRole: "Trainer",
    marketplaceId: null,
    title: "AI Facilitation Workshop",
    category: "AI",
    format: "External LIVE",
    price: 80,
    description:
      "A practical live workshop for facilitating responsible AI learning.",
    modules: ["Workshop preparation", "Live facilitation", "Reflection"],
    provider: "Zoom",
    startsAt: "2026-09-20T20:00",
    timezone: "Asia/Singapore (GMT+8)",
    replay: "May be shared by Trainer",
    status: "Draft",
    visibility: "Public marketplace",
    updatedAt: "18 Aug 2026",
  },
  {
    id: "PUB-CONTENT-AI",
    kind: "content",
    ownerRole: "Creator",
    marketplaceId: "ai-study-notes",
    title: "AI Study Notes",
    category: "AI",
    format: "PDF",
    price: 30,
    description:
      "Downloadable notes created for beginner AI learners, with concise examples and revision prompts.",
    fileName: "ai-study-notes.pdf",
    status: "Published",
    visibility: "Public marketplace",
    updatedAt: "17 Aug 2026",
  },
  {
    id: "PUB-CONTENT-PIXEL",
    kind: "content",
    ownerRole: "Creator",
    marketplaceId: null,
    title: "Pixel Art Guide",
    category: "Design",
    format: "Video",
    price: 60,
    description:
      "A visual guide to silhouettes, colour ramps and animation-ready sprites.",
    fileName: "pixel-art-guide.mp4",
    status: "Draft",
    visibility: "Hidden link only",
    updatedAt: "16 Aug 2026",
  },
];

export const contents = [
  {
    id: "ai-study-notes",
    title: "AI Study Notes",
    creator: "Creator A",
    category: "AI",
    type: "PDF",
    price: 30,
    rating: 4.8,
    purchased: true,
    description:
      "Downloadable notes created for beginner AI learners, with concise examples and revision prompts.",
  },
  {
    id: "pixel-art-guide",
    title: "Pixel Art Guide",
    creator: "Creator B",
    category: "Design",
    type: "Video",
    price: 60,
    rating: 4.6,
    purchased: true,
    description:
      "A visual guide to silhouettes, colour ramps, clusters and animation-ready sprites.",
  },
  {
    id: "js-practice-pack",
    title: "JS Practice Pack",
    creator: "Creator C",
    category: "Code",
    type: "Files",
    price: 45,
    rating: 4.5,
    purchased: false,
    description:
      "A practical exercise pack containing starter files, tasks and reference solutions.",
  },
  {
    id: "game-ui-template",
    title: "Game UI Template",
    creator: "Creator D",
    category: "Design",
    type: "Asset",
    price: 90,
    rating: 4.7,
    purchased: false,
    description:
      "A flexible UI asset set for prototyping menus, inventories and status panels.",
  },
];

export const baseTransactions = [
  {
    id: "TX-0716-01",
    createdAt: "2026-07-16T09:30:00+08:00",
    date: "16 Jul 2026",
    type: "Course purchase",
    item: "Cybersecurity Intro",
    category: "Spending",
    amount: -100,
    balance: 320,
    status: "Completed",
  },
  {
    id: "TX-0715-01",
    createdAt: "2026-07-15T14:15:00+08:00",
    date: "15 Jul 2026",
    type: "Points top-up",
    item: "Credit / Debit Card",
    category: "Top-up",
    amount: 100,
    balance: 420,
    status: "Completed",
  },
  {
    id: "TX-0714-01",
    createdAt: "2026-07-14T18:20:00+08:00",
    date: "14 Jul 2026",
    type: "Trainer income",
    item: "Web Design Bootcamp",
    category: "Income",
    amount: 120,
    balance: 320,
    status: "Completed",
  },
  {
    id: "TX-0713-01",
    createdAt: "2026-07-13T11:45:00+08:00",
    date: "13 Jul 2026",
    type: "Course refund",
    item: "Cybersecurity Intro",
    category: "Refund",
    amount: 100,
    balance: 200,
    status: "Approved",
  },
  {
    id: "TX-0712-01",
    createdAt: "2026-07-12T08:10:00+08:00",
    date: "12 Jul 2026",
    type: "Content purchase",
    item: "AI Study Notes",
    category: "Spending",
    amount: -30,
    balance: 100,
    status: "Completed",
  },
];

export const refundRequests = [
  {
    id: "RF-1001",
    user: "Alice",
    courseId: "cybersecurity",
    course: "Cybersecurity Intro",
    basis: "Before 72-hour deadline",
    paid: 100,
    eligibility: "Eligible",
    reason: "Schedule conflict",
    status: "Pending",
    submittedAt: "12 Jul 2026",
  },
  {
    id: "RF-1002",
    user: "Ben",
    courseId: "web-design",
    course: "Web Design Bootcamp",
    basis: "25% watched",
    paid: 120,
    eligibility: "Not eligible",
    reason: "Course was not suitable",
    status: "Pending",
    submittedAt: "11 Jul 2026",
  },
  {
    id: "RF-1003",
    user: "Chloe",
    courseId: "ai-basics",
    course: "AI Basics",
    basis: "11% watched · 10% limit",
    paid: 80,
    eligibility: "Not eligible",
    reason: "Purchased by mistake",
    status: "Pending",
    submittedAt: "10 Jul 2026",
  },
];

export const roleApplications = [
  {
    id: "RA-2001",
    user: "Amelia Tan",
    type: "Trainer",
    category: "AI",
    portfolio: "AI teaching portfolio",
    experience: "3 years teaching adult learners",
    reason: "Create practical AI literacy courses",
    status: "Pending",
    submittedAt: "12 Jul 2026",
  },
  {
    id: "RA-2002",
    user: "Jordan Lee",
    type: "Creator",
    category: "Design",
    portfolio: "UI and illustration portfolio",
    experience: "Independent digital creator",
    reason: "Publish reusable design resources",
    status: "Pending",
    submittedAt: "11 Jul 2026",
  },
];

export const author = {
  id: "trainer-a",
  name: "Alex Morgan",
  role: "Trainer · Creator",
  bio: "AI educator and learning designer focused on practical, beginner-friendly teaching.",
  specialty: "AI literacy, prompt design and digital learning",
  rating: 4.8,
  followers: "1.2k",
};
